name: helloworld
description: Dart gRPC sample client and server.
homepage: https://github.com/dart-lang/grpc-dart

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  async: ^2.2.0
  grpc: ^2.0.0
  protobuf: ^0.13.12

dev_dependencies:
  test: ^1.6.4
